config/routes.rb
ShinyNinja::Application.routes.draw do

  resources :testmodels

  get "/projects_users/confirm_project_evaluator", :controller => "projects_users", :action => "confirm_project_evaluator"

  authenticated do
    get "/", :controller => "indices", :action => "start"
  end

  get "/", :controller => "indices", :action => "home"
  get "/index/start", :controller => "indices", :action => "start"
  get "/index/home", :controller => "indices", :action => "home"
  get "/index/impressum", :controller => "indices", :action => "impressum"
  get "/index/impressum", :controller => "devise/indices", :action => "impressum"
  get "/index/administrator", :controller => "indices", :action => "administrator"
  get "/index/timetracker", :controller => "indices", :action => "timetracker"
  get "/index/projectevaluator", :controller => "indices", :action => "projectevaluator"

  get "/projects/:id/archive", :controller => "projects", :action => "archive"
  get "/projects/:id/restore", :controller => "projects", :action => "restore"
  get "/reports/:id/archive", :controller => "reports", :action => "archive"
  get "/reports/:id/restore", :controller => "reports", :action => "restore"

  resources :bills

  resources :services

  resources :reports

  resources :projects_users

  resources :projects

  devise_for :users, :controllers => {:registrations => :registrations, :passwords => :passwords}

  resources :customers

  resources :users

  root :to => 'indices#start'

end

app/models/testmodel.rb
class Testmodel < ActiveRecord::Base
end

app/controllers/testmodels_controller.rb
class TestmodelsController < ApplicationController
  before_action :set_testmodel, only: [:show, :edit, :update, :destroy]

  # GET /testmodels
  def index
    @testmodels = Testmodel.all
  end

  # GET /testmodels/1
  def show
  end

  # GET /testmodels/new
  def new
    @testmodel = Testmodel.new
  end

  # GET /testmodels/1/edit
  def edit
  end

  # POST /testmodels
  def create
    @testmodel = Testmodel.new(testmodel_params)

    if @testmodel.save
      redirect_to @testmodel, notice: 'Testmodel was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /testmodels/1
  def update
    if @testmodel.update(testmodel_params)
      redirect_to @testmodel, notice: 'Testmodel was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /testmodels/1
  def destroy
    @testmodel.destroy
    redirect_to testmodels_url, notice: 'Testmodel was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_testmodel
      @testmodel = Testmodel.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def testmodel_params
      params.require(:testmodel).permit(:teststring, :testcheck, :testnumber)
    end
end

app/helpers/testmodels_helper.rb
module TestmodelsHelper
end

app/views/testmodels/_form.html.erb
<%= form_for(@testmodel) do |f| %>
  <% if @testmodel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@testmodel.errors.count, "error") %> prohibited this testmodel from being saved:</h2>

      <ul>
      <% @testmodel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :teststring %><br>
    <%= f.text_field :teststring %>
  </div>
  <div class="field">
    <%= f.label :testcheck %><br>
    <%= f.check_box :testcheck %>
  </div>
  <div class="field">
    <%= f.label :testnumber %><br>
    <%= f.text_field :testnumber %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/testmodels/edit.html.erb
<h1>Editing testmodel</h1>

<%= render 'form' %>

<%= link_to 'Show', @testmodel %> |
<%= link_to 'Back', testmodels_path %>

app/views/testmodels/index.html.erb
<h1>Listing testmodels</h1>

<table>
  <thead>
    <tr>
      <th>Teststring</th>
      <th>Testcheck</th>
      <th>Testnumber</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @testmodels.each do |testmodel| %>
      <tr>
        <td><%= testmodel.teststring %></td>
        <td><%= testmodel.testcheck %></td>
        <td><%= testmodel.testnumber %></td>
        <td><%= link_to 'Show', testmodel %></td>
        <td><%= link_to 'Edit', edit_testmodel_path(testmodel) %></td>
        <td><%= link_to 'Destroy', testmodel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Testmodel', new_testmodel_path %>

app/views/testmodels/new.html.erb
<h1>New testmodel</h1>

<%= render 'form' %>

<%= link_to 'Back', testmodels_path %>

app/views/testmodels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Teststring:</strong>
  <%= @testmodel.teststring %>
</p>

<p>
  <strong>Testcheck:</strong>
  <%= @testmodel.testcheck %>
</p>

<p>
  <strong>Testnumber:</strong>
  <%= @testmodel.testnumber %>
</p>

<%= link_to 'Edit', edit_testmodel_path(@testmodel) %> |
<%= link_to 'Back', testmodels_path %>