config/routes.rb
ShinyNinja::Application.routes.draw do

  resources :testmodels

  get "/projects_users/confirm_project_evaluator", :controller => "projects_users", :action => "confirm_project_evaluator"

  authenticated do
    get "/", :controller => "indices", :action => "start"
  end

  get "/", :controller => "indices", :action => "home"
  get "/index/start", :controller => "indices", :action => "start"
  get "/index/home", :controller => "indices", :action => "home"
  get "/index/impressum", :controller => "indices", :action => "impressum"
  get "/index/impressum", :controller => "devise/indices", :action => "impressum"
  get "/index/administrator", :controller => "indices", :action => "administrator"
  get "/index/timetracker", :controller => "indices", :action => "timetracker"
  get "/index/projectevaluator", :controller => "indices", :action => "projectevaluator"

  get "/projects/:id/archive", :controller => "projects", :action => "archive"
  get "/projects/:id/restore", :controller => "projects", :action => "restore"
  get "/reports/:id/archive", :controller => "reports", :action => "archive"
  get "/reports/:id/restore", :controller => "reports", :action => "restore"

  resources :bills

  resources :services

  resources :reports

  resources :projects_users

  resources :projects

  devise_for :users, :controllers => {:registrations => :registrations, :passwords => :passwords}

  resources :customers

  resources :users

  root :to => 'indices#start'

end

app/views/layouts/_alerts.html.erb
# encoding: UTF-8

<% if notice.present? || params[:notice].present? %>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= notice %> <%= params[:notice] %>
  </div>
<% end %>

<% if alert.present? || params[:alert].present? %>
  <div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= alert %> <%= params[:alert] %>
  </div>
<% end %>

app/views/layouts/_breadcrumbs.html.erb
# encoding: UTF-8

<ul class="breadcrumb">
  <%= render_breadcrumbs %>
</ul>

app/views/layouts/_footer.html.erb
# encoding: UTF-8


Copyright © koriath.org · <%= link_to("GitHub", "https://github.com/protoswype/shiny_ninja", :target => "_blank") %> · <%= link_to("Releases", "https://github.com/prog4fun/shiny_ninja/releases", :target => "_blank") %> · <%= link_to("Impressum", :controller => "indices", :action => "impressum", :target => "_blank") %>

app/views/layouts/_navigation.html.erb
# encoding: UTF-8
<ul class="nav navbar-nav">

  <% if user_signed_in? %>

      <% if current_user.is? :time_tracker %>
          <li class="<%= @active_menu == "report" ? "active" : "nav" %>"><%= link_to t('activerecord.models.reports'), reports_path %></li>
          <li class='<%= @active_menu == "project" ? "active" : "nav" %>'><%= link_to t('activerecord.models.projects'), projects_path %></li>
          <li class='<%= @active_menu == "customer" ? "active" : "nav" %>'><%= link_to t('activerecord.models.customers'), customers_path %></li>
          <li class='<%= @active_menu == "service" ? "active" : "nav" %>'><%= link_to t('activerecord.models.services'), services_path %></li>
          <li class='<%= @active_menu == "bill" ? "active" : "nav" %>'><%= link_to t('activerecord.models.bills'), bills_path %></li>
      <% end %>
      <% if can? :index, User %>
          <li class='<%= @active_menu == "user" ? "active" : "nav" %>'><%= link_to t('activerecord.models.users'), :controller => "users", :action => "index" %></li>
      <% end %>

      <% if current_user.is? :project_evaluator %>
          <li class="dropdown <%= @active_menu == "evaluate_project" ? "active" : "nav" %>">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t("labels.report.projects_to_evaluate") %>
              <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <% projects_users = current_user.evaluate_projects %>
              <% if projects_users.present? %>
                  <% projects_users.each do |pu| %>
                      <li>
                        <a href="<%= url_for(:controller => "reports", :action => "index", :projects_user => pu) %>"><%= pu.name %>
                          (<%= pu.user.lastname %>)</a></li>
                  <% end %>
              <% else %>
                  <li><a href="#">Noch kein Projekt vorhanden</a></li>
              <% end %>
            </ul>
          </li>
      <% end %>

      <li class='visible-xs'><a href="<%= user_path(current_user) %>"><%= t('labels.person.my_account') %></a></li>
      <li class='nav danger visible-xs'>
        <a href="<%= destroy_user_session_path %>" data-method="delete" rel="nofollow"><%= t('labels.actions.logout') %></a>
      </li>

  <% else %>
      <ul class="nav navbar-nav visible-xs">
        <li class='nav success'><%= link_to(t('labels.actions.login'), new_user_session_path) %></li>
      </ul>
      <ul class="nav navbar-nav visible-xs">
        <li class='nav info'><%= link_to(t('labels.actions.sign_up'), new_registration_path(resource_name)) %></li>
      </ul>
  <% end %>
</ul>

app/views/layouts/_sidebar.html.erb
# encoding: UTF-8

<%  if @search_bar == true %>
  <b> <font size="+2"> Downloads </font> </b>
  <br/>
  <%  if @active_menu == "report" %>
    <%= link_to 'CSV-File', :action => "index", :data => params[:search], :format => :csv %>
  <% end %>
<% end %>

app/views/layouts/_user_control.html.erb
# encoding: UTF-8
<ul class="nav navbar-nav navbar-right hidden-xs">
  <% if user_signed_in? %>

    <div class="btn-group hidden-xs">
      <a class="btn btn-default" href="<%= user_path(current_user) %>">Hey, <%= current_user.firstname %>!</a>
      <a class="btn btn-danger" href="<%= destroy_user_session_path %>" data-method="delete" rel="nofollow"><%= t('labels.actions.logout') %></a>
    </div>

  <% else %>

    <%= form_for(resource, :as => resource_name, :url => session_path(resource_name), :html => {:class => "navbar-form navbar-right"}) do |f| %>
      <div class="form-group">
        <%= f.text_field :login, :class => "form-control", placeholder: "#{t("activerecord.attributes.user.login")}", size: 20  %>
      </div>
      <div class="form-group">
        <%= f.password_field :password, :class => "form-control", placeholder: "#{t("activerecord.attributes.user.password")}", size: 20  %>
      </div>

      <% if devise_mapping.rememberable? -%>
        <%= f.hidden_field :remember_me, :value => true %>
      <% end -%>

      <div class="btn-group">
        <button type="submit" class="btn btn-success hidden-xs"><%= t("labels.actions.login") %></button>
        <button type="button" class="btn btn-success hidden-xs dropdown-toggle" data-toggle="dropdown">
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
          <%= render "devise/shared/links" %>
        </ul>
      </div>


    <% end %>

  <% end %>
</ul>

app/views/layouts/application.html.erb
# encoding: UTF-8 <!DOCTYPE html>
<html class="no-js">
  <head>
    <title>ShinyNinja</title>   
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <%#= favicon_link_tag 'webapp/AppIcon57x57.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '57x57' %>
    <%#= favicon_link_tag 'webapp/AppIcon57x57@2x.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '114x114' %>
    <%#= favicon_link_tag 'webapp/AppIcon60x60.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '60x60' %>
    <%#= favicon_link_tag 'webapp/AppIcon60x60@2x.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '120x120' %>
    <%#= favicon_link_tag 'webapp/AppIcon72x72.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '72x72' %>
    <%#= favicon_link_tag 'webapp/AppIcon72x72@2x.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '144x144' %>
    <%#= favicon_link_tag 'webapp/AppIcon76x76.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '76x76' %>
    <%#= favicon_link_tag 'webapp/AppIcon76x76@2x.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '152x152' %>

    <%= favicon_link_tag 'favicons/clock_64.ico' %>
    <%= favicon_link_tag 'favicons/clock_32', rel: 'apple-touch-icon-precomposed', sizes: '32x32' %>
    <%= favicon_link_tag 'favicons/clock_48', rel: 'apple-touch-icon-precomposed', sizes: '48x48' %>
    <%= favicon_link_tag 'favicons/clock_64', rel: 'apple-touch-icon-precomposed', sizes: '64x64' %>
    <%= favicon_link_tag 'favicons/clock_128', rel: 'apple-touch-icon-precomposed', sizes: '128x128' %>
    <%= favicon_link_tag 'favicons/clock_256', rel: 'apple-touch-icon-precomposed', sizes: '256x256' %>

    <%= csrf_meta_tags %>


  </head>
  <body>

    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "ShinyNinja", root_path, class: "navbar-brand" %>
        </div>

        <div class="navbar-collapse collapse">        
          <%= render "layouts/navigation" %>
          <%= render "layouts/user_control" %>
        </div>
      </nav>

  <%#= render "layouts/breadcrumbs" %> 
      <%= render "layouts/alerts" %> 

      <div id="<%= params[:controller] %>-<%= params[:action] %>" class="container">
        <%= yield %>
      </div>


      <footer class="modal-footer" role="contentinfo">
        <div class="container">
          <%= render "layouts/footer" %>

        </div>
      </footer>

    </body>
  </html>